# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0002_auto_20170625_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva'),
        ),
    ]
