# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0003_auto_20170625_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='codigo_comprobante',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
