# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20170625_1732'),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereserva',
            name='catalogo',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='cancha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cancha'),
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='implementos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Implemento'),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.Reserva'),
        ),
    ]
