# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20170625_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallereserva',
            old_name='costo',
            new_name='costo_cancha',
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='costo_implemento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
