# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20170625_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallereserva',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
