# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_detallereserva_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallereserva',
            name='codigo_reserva',
        ),
    ]
