# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_auto_20170625_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='costo_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallereserva',
            name='costo_implemento',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
