# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_auto_20170625_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallereserva',
            old_name='costo_cancha',
            new_name='costo',
        ),
        migrations.RemoveField(
            model_name='detallereserva',
            name='costo_implemento',
        ),
    ]
