# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_auto_20170625_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
    ]
