# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.IntegerField()),
                ('logo', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
