# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Empresa'),
        ),
    ]
