# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20170623_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Archivos',
                'verbose_name': 'Archivo',
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado_reserva', models.CharField(choices=[('0', 'libre'), ('1', 'Reservado'), ('2', 'Ocupado')], default=0, max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.TipoCancha')),
            ],
            options={
                'verbose_name_plural': 'Canchas',
                'verbose_name': 'Cancha',
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cancha'),
        ),
    ]
