# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20170623_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Cancha')),
            ],
            options={
                'verbose_name_plural': 'Catalogos',
                'verbose_name': 'Catalogo',
            },
        ),
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('despcripcion', models.IntegerField()),
                ('logo', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Implementos',
                'verbose_name': 'Implemento',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido_paterno', models.CharField(max_length=60)),
                ('apellido_materno', models.CharField(max_length=60)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
            },
        ),
        migrations.AddField(
            model_name='catalogo',
            name='implemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.Implemento'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Local'),
        ),
    ]
