# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20170625_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implemento',
            name='despcripcion',
            field=models.TextField(),
        ),
    ]
