# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_implemento_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implemento',
            name='costo',
            field=models.IntegerField(),
        ),
    ]
